/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

//to change to PSP in thread mode first initialise PSP using inline assembly
/* ------------------------------------------- SRAM END OR STACK START OR MSP START
 *
 *
 *
 * 512KB
 *
 *
 *
 * --------------------------------------------MSP END PSP START
 *
 *
 *
 *
 *
 * 512 KB
 *
 *
 *
 *
 * ---------------------------------------------- PSP END
// */
//#define SRAM_START 0x20000000U
//#define SRAM_SIZE  (128*1024)
//#define SRAM_END   ((SRAM_START)+(SRAM_SIZE))
//#define STACK_START SRAM_END
//#define MSP_START	STACK_START
//#define MSP_END     (MSP_END+512)
//#define PSP_START 	MSP_END
//#define PSP_END		(MSP_END+512)


int sum(int a,int b, int c,int d){
	return a+b+c+d;
}
__attribute((naked))void generate_exception(void){
	__asm volatile ("SVC #0X2");


}
__attribute__((naked))void change_to_psp(void)
{
	__asm volatile (".equ SRAM_END, ((0x20000000U)+(128*1024))\n"
					".equ PSP_START, ((SRAM_END)-512)\n"
					"LDR R0,=PSP_START\n"
					"MSR PSP,R0\n"
					"MOV R1,#0x02\n"
					"MSR CONTROL,R1\n"
					"BX LR");
}
void SVC_Handler (void)
{
	printf("In SVC HANDLER - HANDLER MODE");
}
int main(void)
{

	//change to sp =psp
	change_to_psp();
	int result;
	result=sum(1,2,3,4);
	printf("result:%d",result);
	generate_exception();
    /* Loop forever */
	for(;;);
}
